import type { Config, Formation, Preset, Skill, Weapon } from '../sim/types';

export const VERSION = 'orchestra-1';
export const DT = 1 / 60;
export const DEFAULT_CONFIG: Config = {
  seed: 1307,
  atbRate: 0.85,
  moveTime: 0.6,
  shiftTime: 0.45,
  slowDrain: 4,
  stopDrain: 12,
  enemyPower: 1,
  uiMode: 'separate',
  encounter: 1,
};
export const ROLE_NAMES = { A: '削る・維持', B: '崩す', S: '支援' };
export const ROW_NAMES = { front: '前列', back: '後列' };
export const SKILLS: Record<string, Skill> = Object.fromEntries(
  (
    [
      {
        id: 'slash',
        name: '斬撃',
        cost: 1,
        cast: 0.35,
        power: 85,
        chain: 3,
        hold: 3.8,
        effect: 'damage',
        target: 'enemy',
        description: '単体を斬り、チェインの減衰を抑える。',
      },
      {
        id: 'sweep',
        name: '円弧斬り',
        cost: 2,
        cast: 0.9,
        power: 130,
        chain: 4,
        hold: 4,
        effect: 'damage',
        target: 'enemyRow',
        description: '指定列に着弾した時点で、その列にいる敵すべてを斬る。',
      },
      {
        id: 'shot',
        name: '射撃',
        cost: 1,
        cast: 0.4,
        power: 76,
        chain: 3,
        hold: 3.8,
        effect: 'damage',
        target: 'enemy',
        description: '単体を射抜く。後列でも威力が落ちない。',
      },
      {
        id: 'volley',
        name: '一斉射',
        cost: 2,
        cast: 1,
        power: 118,
        chain: 4,
        hold: 3.8,
        effect: 'damage',
        target: 'enemyRow',
        description: '指定列へ矢を放つ。敵を集めるほど総ダメージが増える。',
      },
      {
        id: 'spark',
        name: '砕光',
        cost: 1,
        cast: 0.45,
        power: 28,
        chain: 15,
        hold: 0.6,
        effect: 'damage',
        target: 'enemy',
        description: '単体のチェインを伸ばす。前列ではチェイン効果が増す。',
      },
      {
        id: 'rain',
        name: '星の雨',
        cost: 2,
        cast: 1.15,
        power: 40,
        chain: 22,
        hold: 0.8,
        effect: 'damage',
        target: 'enemyRow',
        description: '指定列に光を降らせ、複数の敵を同時に崩す。',
      },
      {
        id: 'jab',
        name: '砕突',
        cost: 1,
        cast: 0.35,
        power: 32,
        chain: 14,
        hold: 0.6,
        effect: 'damage',
        target: 'enemy',
        description: '単体を突き、チェインを伸ばす。',
      },
      {
        id: 'pull',
        name: '引き寄せ',
        cost: 2,
        cast: 0.55,
        power: 38,
        chain: 19,
        hold: 0.7,
        effect: 'pull',
        target: 'enemy',
        description: '敵を前列へ引く。移動中断可能な構えを崩し、後列防護から外す。',
      },
      {
        id: 'smash',
        name: '砕打',
        cost: 1,
        cast: 0.55,
        power: 42,
        chain: 16,
        hold: 0.6,
        effect: 'damage',
        target: 'enemy',
        description: '重い一撃でチェインを伸ばす。',
      },
      {
        id: 'push',
        name: '轟砕',
        cost: 2,
        cast: 1.1,
        power: 68,
        chain: 25,
        hold: 0.8,
        effect: 'push',
        target: 'enemy',
        description: '敵を後列へ押す。前列の防護役を退かせる。',
      },
      {
        id: 'heal',
        name: '小さな祈り',
        cost: 1,
        cast: 0.45,
        power: 190,
        chain: 0,
        hold: 0,
        effect: 'heal',
        target: 'ally',
        description: '味方一人のHPを回復。自動行動では負傷した味方を選ぶ。',
      },
      {
        id: 'greatHeal',
        name: '祝福の鐘',
        cost: 2,
        cast: 0.9,
        power: 460,
        chain: 0,
        hold: 0,
        effect: 'heal',
        target: 'ally',
        description: '味方一人を大きく回復。必要なATBが貯まるまで予約できる。',
      },
      {
        id: 'ward',
        name: '護りの誓い',
        cost: 1,
        cast: 0.3,
        power: 0,
        chain: 0,
        hold: 0,
        effect: 'shield',
        target: 'ally',
        description: '味方一人の被ダメージを6秒間半減する。',
      },
      {
        id: 'rampart',
        name: '列の防壁',
        cost: 2,
        cast: 0.65,
        power: 0,
        chain: 0,
        hold: 0,
        effect: 'shield',
        target: 'allyRow',
        description: '指定列の味方に6秒間の防護。武器を替えても持続する。',
      },
      {
        id: 'evacuate',
        name: '緊急退避',
        cost: 2,
        cast: 0.2,
        power: 0,
        chain: 0,
        hold: 0,
        effect: 'evacuate',
        target: 'allyRow',
        description: '指定列の味方を反対列へ退避。実行中の技を中断し、ATBは戻らない。',
      },
      {
        id: 'guard',
        name: '防御',
        cost: 0,
        cast: 0.2,
        power: 0,
        chain: 0,
        hold: 0,
        effect: 'guard',
        target: 'self',
        description: '4秒間、自分の被ダメージを半減。準備中の技が終わってから構える。',
      },
      {
        id: 'potion',
        name: '救急薬',
        cost: 0,
        cast: 0.35,
        power: 400,
        chain: 0,
        hold: 0,
        effect: 'potion',
        target: 'ally',
        description: '味方一人を400回復。ラン全体で3個。',
      },
    ] satisfies Skill[]
  ).map((s) => [s.id, s]),
);

export const WEAPONS: Record<string, Weapon> = Object.fromEntries(
  (
    [
      {
        id: 'sword',
        name: '黎明の剣',
        archetype: '剣士',
        role: 'A',
        specialty: '列攻撃',
        glyph: '♜',
        trait: '前列で斬撃威力 +25%',
        melee: true,
        skills: ['slash', 'sweep'],
      },
      {
        id: 'shield',
        name: '誓いの盾槍',
        archetype: '守護騎士',
        role: 'S',
        specialty: '防護',
        glyph: '♖',
        trait: '防護は武器変更後も持続',
        melee: true,
        skills: ['ward', 'rampart'],
      },
      {
        id: 'staff',
        name: '星詠みの杖',
        archetype: '魔術師',
        role: 'B',
        specialty: '列崩し',
        glyph: '✧',
        trait: '前列でチェイン効率 +25%',
        melee: false,
        skills: ['spark', 'rain'],
      },
      {
        id: 'bow',
        name: '風渡りの弓',
        archetype: '射手',
        role: 'A',
        specialty: '遠隔・列攻撃',
        glyph: '⌁',
        trait: '後列でも威力を維持',
        melee: false,
        skills: ['shot', 'volley'],
      },
      {
        id: 'bell',
        name: '巡礼の祈祷鈴',
        archetype: '祈祷師',
        role: 'S',
        specialty: '回復',
        glyph: '♧',
        trait: '負傷した味方を自動回復',
        melee: false,
        skills: ['heal', 'greatHeal'],
      },
      {
        id: 'hook',
        name: '渡り鳥の鉤槍',
        archetype: '鉤槍使い',
        role: 'B',
        specialty: '引き寄せ',
        glyph: '↟',
        trait: '後衛を前列へ引き出す',
        melee: true,
        skills: ['jab', 'pull'],
      },
      {
        id: 'hammer',
        name: '轟砕の槌',
        archetype: '破砕士',
        role: 'B',
        specialty: '押し出し',
        glyph: '⚒',
        trait: '前列のチェイン効果がさらに +20%',
        melee: true,
        skills: ['smash', 'push'],
        bonus: 'frontChain',
      },
      {
        id: 'starbow',
        name: '流星の弓',
        archetype: '射手',
        role: 'A',
        specialty: 'ブレイク追撃',
        glyph: '⌁',
        trait: 'ブレイク中のダメージ +35%',
        melee: false,
        skills: ['shot', 'volley'],
        bonus: 'breakDamage',
      },
      {
        id: 'banner',
        name: '帰還の軍旗',
        archetype: '旗手',
        role: 'S',
        specialty: '緊急退避',
        glyph: '⚑',
        trait: '0.2秒で列ごと救援',
        melee: false,
        skills: ['ward', 'evacuate'],
      },
    ] satisfies Weapon[]
  ).map((w) => [w.id, w]),
);

export const PRESETS: Preset[] = [
  { name: '均衡の調べ', slots: [0, 0, 0], rows: ['front', 'back', 'back'] },
  { name: '崩しの連奏', slots: [0, 0, 1], rows: ['front', 'front', 'back'] },
  { name: '終幕の一撃', slots: [0, 1, 1], rows: ['front', 'back', 'back'] },
  { name: '守りの祈り', slots: [1, 0, 0], rows: ['back', 'back', 'back'] },
];
export const FORMATIONS: Formation[] = [
  { name: '全員後列', rows: ['back', 'back', 'back'] },
  { name: '前後分散', rows: ['front', 'back', 'back'] },
  { name: '全員前列', rows: ['front', 'front', 'front'] },
];
