import type { Config, Formation, Preset, Skill, Weapon } from '../sim/types';

export const VERSION = 'orchestra-5';
export const DT = 1 / 60;
export const BATTLE_TIMING = {
  enemyWindupScale: 1.6,
  enemyIntervalScale: 1.5,
  breakDuration: 12,
  chainDecay: 7,
  guardDuration: 6,
  shieldDuration: 9,
  steadfastDuration: 3,
  handoffSlow: 0.8,
};
export const DEFAULT_CONFIG: Config = {
  atbMax: 4,
  seed: 1307,
  atbRate: 0.55,
  moveTime: 0.85,
  shiftTime: 0.65,
  slowDrain: 4,
  stopDrain: 12,
  enemyPower: 1,
  uiMode: 'separate',
  encounter: 1,
};
export const ROLE_NAMES = { A: '削る・維持', B: '崩す', D: '受け止める', S: '状態を整える' };
export const ROW_NAMES = { front: '前列', back: '後列' };
export const SKILLS: Record<string, Skill> = Object.fromEntries(
  (
    [
      {
        id: 'slash',
        name: '斬撃',
        cost: 1,
        cast: 0.9,
        recovery: 1.0,
        power: 85,
        chain: 3,
        hold: 6.08,
        effect: 'damage',
        target: 'enemy',
        description: '単体を斬り、チェインの減衰を抑える。',
      },
      {
        id: 'sweep',
        name: '円弧斬り',
        cost: 2,
        cast: 1.8,
        recovery: 1.2,
        power: 130,
        chain: 4,
        hold: 6.4,
        effect: 'damage',
        target: 'enemyRow',
        description: '指定列に着弾した時点で、その列にいる敵すべてを斬る。',
      },
      {
        id: 'shot',
        name: '射撃',
        cost: 1,
        cast: 1.0,
        recovery: 0.9,
        power: 76,
        chain: 3,
        hold: 6.08,
        effect: 'damage',
        target: 'enemy',
        description: '単体を射抜く。後列でも威力が落ちない。',
      },
      {
        id: 'volley',
        name: '一斉射',
        cost: 2,
        cast: 1.9,
        recovery: 1.2,
        power: 118,
        chain: 4,
        hold: 6.08,
        effect: 'damage',
        target: 'enemyRow',
        description: '指定列へ矢を放つ。敵を集めるほど総ダメージが増える。',
      },
      {
        id: 'spark',
        name: '砕光',
        cost: 1,
        cast: 1.0,
        recovery: 0.9,
        power: 28,
        chain: 15,
        hold: 0.96,
        effect: 'damage',
        target: 'enemy',
        description: '単体のチェインを伸ばす。前列ではチェイン効果が増す。',
      },
      {
        id: 'rain',
        name: '星の雨',
        cost: 2,
        cast: 2.0,
        recovery: 1.2,
        power: 40,
        chain: 22,
        hold: 1.28,
        effect: 'damage',
        target: 'enemyRow',
        description: '指定列に光を降らせ、複数の敵を同時に崩す。',
      },
      {
        id: 'jab',
        name: '砕突',
        cost: 1,
        cast: 0.9,
        recovery: 1.0,
        power: 32,
        chain: 14,
        hold: 0.96,
        effect: 'damage',
        target: 'enemy',
        description: '単体を突き、チェインを伸ばす。',
      },
      {
        id: 'pull',
        name: '引き寄せ',
        cost: 2,
        cast: 1.1,
        recovery: 1.1,
        power: 38,
        chain: 19,
        hold: 1.12,
        effect: 'pull',
        target: 'enemy',
        description: '敵を前列へ引く。移動中断可能な構えを崩し、後列防護から外す。',
      },
      {
        id: 'smash',
        name: '砕打',
        cost: 1,
        cast: 1.15,
        recovery: 1.05,
        power: 42,
        chain: 16,
        hold: 0.96,
        effect: 'damage',
        target: 'enemy',
        description: '重い一撃でチェインを伸ばす。',
      },
      {
        id: 'push',
        name: '轟砕',
        cost: 2,
        cast: 1.8,
        recovery: 1.2,
        power: 68,
        chain: 25,
        hold: 1.28,
        effect: 'push',
        target: 'enemy',
        description: '敵を後列へ押す。前列の防護役を退かせる。',
      },
      {
        id: 'heal',
        name: '小さな祈り',
        cost: 1,
        cast: 1.2,
        recovery: 0.9,
        power: 190,
        chain: 0,
        hold: 0.0,
        effect: 'heal',
        target: 'ally',
        description: '味方一人のHPを回復。自動行動では負傷した味方を選ぶ。',
      },
      {
        id: 'greatHeal',
        name: '祝福の鐘',
        cost: 2,
        cast: 1.9,
        recovery: 1.2,
        power: 460,
        chain: 0,
        hold: 0.0,
        effect: 'heal',
        target: 'ally',
        description: '味方一人を大きく回復。必要なATBが貯まるまで予約できる。',
      },
      {
        id: 'ward',
        name: '護りの誓い',
        cost: 1,
        cast: 0.7,
        recovery: 0.9,
        power: 0,
        chain: 0,
        hold: 0.0,
        effect: 'shield',
        target: 'ally',
        description: '味方一人の被ダメージを9秒間半減する。',
      },
      {
        id: 'rampart',
        name: '列の防壁',
        cost: 2,
        cast: 1.2,
        recovery: 1.1,
        power: 0,
        chain: 0,
        hold: 0.0,
        effect: 'shield',
        target: 'allyRow',
        description: '指定列の味方に9秒間の防護。武器を替えても持続する。',
      },
      {
        id: 'evacuate',
        name: '緊急退避',
        cost: 2,
        cast: 0.45,
        recovery: 1.15,
        power: 0,
        chain: 0,
        hold: 0.0,
        effect: 'evacuate',
        target: 'allyRow',
        description: '指定列の味方を反対列へ退避。実行中の技を中断し、ATBは戻らない。',
      },
      {
        id: 'guard',
        name: '防御',
        cost: 1,
        cast: 0.4,
        recovery: 1.0,
        power: 0,
        chain: 0,
        hold: 0.0,
        effect: 'guard',
        target: 'self',
        description:
          '1 ATBを消費し、6秒間、自分の被ダメージを半減。準備0.4秒・硬直1秒。実行中の技の硬直とATB充填を待って構える。',
      },
      {
        id: 'potion',
        name: '救急薬',
        cost: 0,
        cast: 0.6,
        recovery: 1.0,
        power: 400,
        chain: 0,
        hold: 0.0,
        effect: 'potion',
        target: 'ally',
        description: '味方一人を400回復。ラン全体で3個。',
      },
    ] satisfies Skill[]
  ).map((s) => [s.id, s]),
);

SKILLS.handoff = {
  id: 'handoff',
  name: 'キャラ交代',
  cost: 1,
  cast: 0.6,
  recovery: 0,
  power: 0,
  chain: 0,
  hold: 0,
  effect: 'handoff',
  target: 'ally',
  description: '先頭で交代。開始時に後続予約を解除する。',
};

export const WEAPONS: Record<string, Weapon> = Object.fromEntries(
  (
    [
      {
        id: 'sword',
        name: '黎明の剣',
        archetype: '剣士',
        role: 'A',
        specialty: '列攻撃',
        glyph: '♜',
        trait: '前列で斬撃威力 +25%',
        melee: true,
        skills: ['slash', 'sweep'],
      },
      {
        id: 'shield',
        name: '誓いの盾槍',
        archetype: '守護騎士',
        role: 'D',
        specialty: '防護',
        glyph: '♖',
        trait: '防護は武器変更後も持続',
        melee: true,
        skills: ['ward', 'rampart'],
      },
      {
        id: 'staff',
        name: '星詠みの杖',
        archetype: '魔術師',
        role: 'B',
        specialty: '列崩し',
        glyph: '✧',
        trait: '前列でチェイン効率 +25%',
        melee: false,
        skills: ['spark', 'rain'],
      },
      {
        id: 'bow',
        name: '風渡りの弓',
        archetype: '射手',
        role: 'A',
        specialty: '遠隔・列攻撃',
        glyph: '⌁',
        trait: '後列でも威力を維持',
        melee: false,
        skills: ['shot', 'volley'],
      },
      {
        id: 'bell',
        name: '巡礼の祈祷鈴',
        archetype: '祈祷師',
        role: 'S',
        specialty: '回復',
        glyph: '♧',
        trait: '負傷した味方を自動回復',
        melee: false,
        skills: ['heal', 'greatHeal'],
      },
      {
        id: 'hook',
        name: '渡り鳥の鉤槍',
        archetype: '鉤槍使い',
        role: 'B',
        specialty: '引き寄せ',
        glyph: '↟',
        trait: '後衛を前列へ引き出す',
        melee: true,
        skills: ['jab', 'pull'],
      },
      {
        id: 'hammer',
        name: '轟砕の槌',
        archetype: '破砕士',
        role: 'B',
        specialty: '押し出し',
        glyph: '⚒',
        trait: '前列のチェイン効果がさらに +20%',
        melee: true,
        skills: ['smash', 'push'],
        bonus: 'frontChain',
      },
      {
        id: 'starbow',
        name: '流星の弓',
        archetype: '射手',
        role: 'A',
        specialty: 'ブレイク追撃',
        glyph: '⌁',
        trait: 'ブレイク中のダメージ +35%',
        melee: false,
        skills: ['shot', 'volley'],
        bonus: 'breakDamage',
      },
      {
        id: 'banner',
        name: '帰還の軍旗',
        archetype: '旗手',
        role: 'S',
        specialty: '緊急退避',
        glyph: '⚑',
        trait: '0.2秒で列ごと救援',
        melee: false,
        skills: ['ward', 'evacuate'],
      },
    ] satisfies Weapon[]
  ).map((w) => [w.id, w]),
);

export const PRESETS: Preset[] = [
  { name: '均衡の調べ', slots: [0, 0, 0], rows: ['front', 'back', 'back'] },
  { name: '崩しの連奏', slots: [0, 0, 1], rows: ['front', 'front', 'back'] },
  { name: '終幕の一撃', slots: [0, 1, 1], rows: ['front', 'back', 'back'] },
  { name: '守りの祈り', slots: [1, 0, 0], rows: ['back', 'back', 'back'] },
];
export const FORMATIONS: Formation[] = [
  { name: '全員後列', rows: ['back', 'back', 'back'] },
  { name: '前後分散', rows: ['front', 'back', 'back'] },
  { name: '全員前列', rows: ['front', 'front', 'front'] },
];
